name: nfc_manager_platform_interface
description: A common platform interface for the nfc_manager plugin.
publish_to: none
version: 1.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_cov_console: ^0.2.2

  # Linter
  cosee_lints: 0.12.0
  dart_code_linter: ^3.0.0
